<a href="https://colab.research.google.com/github/fordeframework/Foxtrot-Web-Scraper/blob/main/lifebear_dataclean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import re

In [16]:
#Define the file path

file_path = '/content/3.6M_lifebear.csv'

#Read the dataset with proper separator and memory optimization
lifebear_initial = pd.read_csv(file_path, low_memory=True)

<ipython-input-16-955b4439aece>:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  lifebear_initial = pd.read_csv(file_path, low_memory=True)

In [17]:
# prompt: generate code to read the first 5 lines and last 5 lines of .csv file "/content/3.6M_lifebear.csv". print the results

# Read the first 5 lines
df_head = pd.read_csv(file_path, nrows=5)
print("First 5 lines:")
print(df_head)

# Read the last 5 lines
df_tail = pd.read_csv(file_path, skiprows=lambda x: x < 5, nrows=5)
print("\nLast 5 lines:")
print(df_tail)

First 5 lines:
   id    login_id              mail_address                          password  \
0   1    sugimoto   sugimoto@lifebear.co.jp  f0bac04aa1b45cf443d722d6f71c0250
1   2         kou  nakanishi@lifebear.co.jp  48207c322ee5bb156ffec9f08c960aaa
2   3      yusuke     yuozawa1208@gmail.com  048261a8024ce51d379eb53cc51aaf33
3   4  entyan1106        endo1106@gmail.com  cd77a9dac26260a104facda5665eb3ab
4   5      kuriki          kuriki@wavy4.com  a026597c294cc48cd20ae361f10cbab1

            created_at          salt birthday_on  gender
0  2012-01-13 22:54:05  yGwBKynnsctI  1984-11-09     0.0
1  2012-01-14 12:48:31  aha6EuRYCDvU  1986-11-13     0.0
2  2012-01-17 15:33:22  PVS59dPWk9BH  1984-12-08     0.0
3  2012-01-17 15:37:02  vLZI6TVCJowN  1987-11-06     0.0
4  2012-01-17 18:52:32  swFznWWk79fg  1986-10-21     0.0

Last 5 lines:
    5         kuriki             kuriki@wavy4.com  \
0   6  mashiyamatest     mashiyama@lifebear.co.jp
1   7        deguchi  masayadeguchi1120@gmail.com
2   8         satomi      sammie.tommie@gmail.com
3   9      sugimoto2    sugimoto_1020@yahoo.co.jp
4  10       yumitaso           yumi1180@gmail.com

   a026597c294cc48cd20ae361f10cbab1  2012-01-17 18:52:32  swFznWWk79fg  \
0  12e83b9e106735267e2addac7756065e  2012-01-17 22:18:54  gY9pUJiWJ51P
1  7549d3174922ff5751f4007c2cb689f9  2012-01-17 23:13:17  pyGHpE75ahpC
2  eeb4e8717d14055d922c1a0efd5e0d24  2012-01-23 22:17:21  GAgqqlJM8mPB
3  0495871de880e58decf74a18dda8392f  2012-02-21 12:06:45  0RiB4v0NMT8G
4  6989d9f78327393c86b9f4e0e0b23000  2012-02-21 13:36:08  XXc6C3XHCCdm

   1986-10-21  0.0
0  1970-01-01  0.0
1         NaN  NaN
2  1970-01-01  1.0
3  1984-11-09  0.0
4  1988-08-11  1.0

In [18]:
#Identify and print the number of missing values in each column

print(lifebear_initial.isnull().sum())

id                    0
login_id              2
mail_address          0
password              0
created_at            0
salt                  0
birthday_on     3294901
gender          1317523
dtype: int64

In [19]:
#Drop rows with duplicate values that exist in both "login_id" and "mail_address" columns

# Identify duplicate rows based on "login_id" and "mail_address"
lifebear_duplicates = lifebear_initial[lifebear_initial.duplicated(subset=["login_id", "mail_address"], keep=False)]

# Save the duplicate rows to a garbage file
lifebear_duplicates.to_csv("/content/lifebear_dup_garbage.csv", index=False)

# Drop the duplicate rows from the original dataframe
lifebear_clean = lifebear_initial.drop_duplicates(subset=["login_id", "mail_address"], keep='first')

# Save the cleaned data to a new csv file
lifebear_clean.to_csv("/content/lifebear_clean.csv", index=False)

In [20]:
lifebear_clean.head(10)

,id,login_id,mail_address,password,created_at,salt,birthday_on,gender
0,1,sugimoto,sugimoto@lifebear.co.jp,f0bac04aa1b45cf443d722d6f71c0250,2012-01-13 22:54:05,yGwBKynnsctI,1984-11-09,0.0
1,2,kou,nakanishi@lifebear.co.jp,48207c322ee5bb156ffec9f08c960aaa,2012-01-14 12:48:31,aha6EuRYCDvU,1986-11-13,0.0
2,3,yusuke,yuozawa1208@gmail.com,048261a8024ce51d379eb53cc51aaf33,2012-01-17 15:33:22,PVS59dPWk9BH,1984-12-08,0.0
3,4,entyan1106,endo1106@gmail.com,cd77a9dac26260a104facda5665eb3ab,2012-01-17 15:37:02,vLZI6TVCJowN,1987-11-06,0.0
4,5,kuriki,kuriki@wavy4.com,a026597c294cc48cd20ae361f10cbab1,2012-01-17 18:52:32,swFznWWk79fg,1986-10-21,0.0
5,6,mashiyamatest,mashiyama@lifebear.co.jp,12e83b9e106735267e2addac7756065e,2012-01-17 22:18:54,gY9pUJiWJ51P,1970-01-01,0.0
6,7,deguchi,masayadeguchi1120@gmail.com,7549d3174922ff5751f4007c2cb689f9,2012-01-17 23:13:17,pyGHpE75ahpC,NaN,NaN
7,8,satomi,sammie.tommie@gmail.com,eeb4e8717d14055d922c1a0efd5e0d24,2012-01-23 22:17:21,GAgqqlJM8mPB,1970-01-01,1.0
8,9,sugimoto2,sugimoto_1020@yahoo.co.jp,0495871de880e58decf74a18dda8392f,2012-02-21 12:06:45,0RiB4v0NMT8G,1984-11-09,0.0
9,10,yumitaso,yumi1180@gmail.com,6989d9f78327393c86b9f4e0e0b23000,2012-02-21 13:36:08,XXc6C3XHCCdm,1988-08-11,1.0

In [21]:
# prompt: can a code be written to verify if a column has valid email address formats?


# Define a function to validate email format
def is_valid_email(email):
    # Expression to allow "-", "_", and "." in the email prefix
    email_regex = r'^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(email_regex, email) is not None

# Assuming 'lifebear_clean' is your DataFrame and 'mail_address' is the email column
lifebear_clean['valid_email'] = lifebear_clean['mail_address'].apply(is_valid_email)

# Filter valid and invalid emails
valid_emails = lifebear_clean[lifebear_clean['valid_email'] == True]
invalid_emails = lifebear_clean[lifebear_clean['valid_email'] == False]

# Save valid emails to 'lifebear_valid_e.csv'
valid_emails.to_csv("/content/lifebear_valid_e.csv", index=False)

# Save invalid emails to 'lifebear_invalid_e.csv'
invalid_emails.to_csv("/content/lifebear_invalid_e.csv", index=False)

# Optionally, print invalid emails
print("Invalid email addresses:")
print(invalid_emails)

<ipython-input-21-ab74dc90405d>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifebear_clean['valid_email'] = lifebear_clean['mail_address'].apply(is_valid_email)

Invalid email addresses:
               id       login_id                       mail_address  \
5720         5784           szn0        rhodd_rosa.00@softbank.ne.J
6551         6616    bejiita7581               katsu-t@cac-net.ne.j
7690         7757           neco             neco0517530@yahoo.co.j
12452       12599     ka14987236                 atjz@softbank.ne.J
13676       13849         mondeo              takao@qa3.so-net.ne.j
...           ...            ...                                ...
3665921  11540467        miwa705             miwa705s.b.cl@icloud.c
3670831  11559359          imasi                             im@s.i
3671204  11560753          imass                             im@s.s
3672455  11565423           cu10                      y_v-1@ezweb.n
3680290  11595387  hidenosukekun  hidehidehidehide-yama@docomo.ne.j

                                 password           created_at          salt  \
5720     ce92162ecd7da309bd6f30d0c0436bac  2012-08-03 15:59:16  iRpidy8Edz9r
6551     85896975c5e0d60fdd4bd0fe9a8839ef  2012-08-04 20:55:27  PbsO1HMvowWn
7690     449f1d4e874e84f3497b489bfc7b4fd6  2012-08-06 08:50:42  5mMYezzamHK1
12452    3a76a029e1702d5888b63edfa96388ba  2012-08-21 22:17:48  R0XxB6XVksqg
13676    a4f20875bcab8bce6f7f6635f04c2bc9  2012-09-01 09:50:54  GBndtfFRv3Fc
...                                   ...                  ...           ...
3665921  42fcd503c34e9bd54424d88fd3e2af7b  2019-02-09 11:34:13  eminWJYicrE7
3670831  cf61788bd17d33f4e751a7db4b11baf8  2019-02-13 12:27:13  dhxdtNG63ejR
3671204  fc3d536de9dcb126b0e4d5e8fb465c4b  2019-02-13 19:43:24  AeAQ8rYFmBoT
3672455  b2f8fdf6966d453a7ad4ad0788280e44  2019-02-14 21:49:34  Q2dKvaOPynK6
3680290  6d8ad97ed65ff80b921e003c52101dfe  2019-02-21 13:16:20  xUleWTbW8DIA

        birthday_on  gender  valid_email
5720     1992-11-30     1.0        False
6551     1963-11-17     0.0        False
7690     1985-05-30     0.0        False
12452    1993-08-11     0.0        False
13676    1967-08-11     0.0        False
...             ...     ...          ...
3665921         NaN     1.0        False
3670831         NaN     NaN        False
3671204         NaN     NaN        False
3672455         NaN     1.0        False
3680290         NaN     NaN        False

[1704 rows x 9 columns]

In [22]:
# Load the CSV file
lifebear_valid_e = pd.read_csv("/content/lifebear_valid_e.csv")

# Convert "login_id" and "mail_address" columns to lowercase
lifebear_valid_e['login_id'] = lifebear_valid_e['login_id'].str.lower()
lifebear_valid_e['mail_address'] = lifebear_valid_e['mail_address'].str.lower()

# Optionally, save the updated DataFrame back to the same or a new file
lifebear_valid_e.to_csv("/content/lifebear_valid_e_update.csv", index=False)

<ipython-input-22-4d2d6598d4a3>:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  lifebear_valid_e = pd.read_csv("/content/lifebear_valid_e.csv")

In [23]:
#prompt: can you write a code to remove the time values from the "created_at" column of the "/content/lifebear_valid_e_update.csv" file path?

# Load the CSV file
lifebear_valid_e_update = pd.read_csv("/content/lifebear_valid_e_update.csv")

# Remove the time from the "created_at" column (keep only the date)
lifebear_valid_e_update['created_at'] = pd.to_datetime(lifebear_valid_e_update['created_at']).dt.date

# Optionally, save the updated DataFrame back to the same or a new file
lifebear_valid_e_update.to_csv("/content/lifebear_valid_e_update.csv", index=False)

<ipython-input-23-d2662ed8740d>:4: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  lifebear_valid_e_update = pd.read_csv("/content/lifebear_valid_e_update.csv")

In [24]:
lifebear_valid_e_update.head(10)

,id,login_id,mail_address,password,created_at,salt,birthday_on,gender,valid_email
0,1,sugimoto,sugimoto@lifebear.co.jp,f0bac04aa1b45cf443d722d6f71c0250,2012-01-13,yGwBKynnsctI,1984-11-09,0.0,True
1,2,kou,nakanishi@lifebear.co.jp,48207c322ee5bb156ffec9f08c960aaa,2012-01-14,aha6EuRYCDvU,1986-11-13,0.0,True
2,3,yusuke,yuozawa1208@gmail.com,048261a8024ce51d379eb53cc51aaf33,2012-01-17,PVS59dPWk9BH,1984-12-08,0.0,True
3,4,entyan1106,endo1106@gmail.com,cd77a9dac26260a104facda5665eb3ab,2012-01-17,vLZI6TVCJowN,1987-11-06,0.0,True
4,5,kuriki,kuriki@wavy4.com,a026597c294cc48cd20ae361f10cbab1,2012-01-17,swFznWWk79fg,1986-10-21,0.0,True
5,6,mashiyamatest,mashiyama@lifebear.co.jp,12e83b9e106735267e2addac7756065e,2012-01-17,gY9pUJiWJ51P,1970-01-01,0.0,True
6,7,deguchi,masayadeguchi1120@gmail.com,7549d3174922ff5751f4007c2cb689f9,2012-01-17,pyGHpE75ahpC,NaN,NaN,True
7,8,satomi,sammie.tommie@gmail.com,eeb4e8717d14055d922c1a0efd5e0d24,2012-01-23,GAgqqlJM8mPB,1970-01-01,1.0,True
8,9,sugimoto2,sugimoto_1020@yahoo.co.jp,0495871de880e58decf74a18dda8392f,2012-02-21,0RiB4v0NMT8G,1984-11-09,0.0,True
9,10,yumitaso,yumi1180@gmail.com,6989d9f78327393c86b9f4e0e0b23000,2012-02-21,XXc6C3XHCCdm,1988-08-11,1.0,True

In [25]:
# Load the CSV file
lifebear_valid_e_update = pd.read_csv("/content/lifebear_valid_e_update.csv")

# Strip leading and trailing whitespace from all columns
lifebear_valid_e_update = lifebear_valid_e_update.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Save the updated DataFrame to a new file named 'lifebear_stripped.csv'
lifebear_valid_e_update.to_csv("/content/lifebear_stripped.csv", index=False)

<ipython-input-25-0324373ecae0>:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  lifebear_valid_e_update = pd.read_csv("/content/lifebear_valid_e_update.csv")

In [26]:
#Chunk the lifebear_stripped csv file into files pf no more than 600,000 lines each for ingestion

def chunk_csv(input_file, chunk_size, output_prefix):
    """
    Chunks a large CSV file into smaller CSV files.

    Args:
        input_file: Path to the input CSV file.
        chunk_size: Maximum number of rows per chunk.
        output_prefix: Prefix for the output file names.
    """
    chunk_num = 0
    for chunk in pd.read_csv(input_file, chunksize=chunk_size):
        output_file = f'{output_prefix}_{chunk_num}.csv'
        chunk.to_csv(output_file, index=False)
        chunk_num += 1
        print(f"Created {output_file}")

# Example usage:
input_file = '/content/lifebear_stripped.csv'
chunk_size = 600000  # Maximum rows per chunk
output_prefix = 'lifebear_cleaned'

chunk_csv(input_file, chunk_size, output_prefix)

Created lifebear_cleaned_0.csv

<ipython-input-26-abb55da1e493>:13: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):

Created lifebear_cleaned_1.csv
Created lifebear_cleaned_2.csv
Created lifebear_cleaned_3.csv
Created lifebear_cleaned_4.csv
Created lifebear_cleaned_5.csv
Created lifebear_cleaned_6.csv